stages:
  - build

build:
  stage: build
  image: python:3.7
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - apt-get -qq -y update
    - apt-get -qq -y install cmake libasound2-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libportmidi-dev
    - pip install pipenv
    - pipenv install --dev
    - (cd audio && pipenv run python setup.py build_ext --inplace)
