[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
pygame = "^2.6.1"
mopyx = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
